/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5



/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
class istream;
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 88
#define YY_END_OF_BUFFER 89
static yyconst short int yy_accept[175] =
    {   0,
        0,    0,   89,   87,    1,    3,    3,   87,   87,   87,
        2,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,    1,    3,    0,    0,    4,
        0,    0,    2,    0,    0,    0,    0,    0,    0,    0,
        0,   70,    0,    0,    8,    0,    0,   14,    0,    0,
        0,    0,    0,    0,    0,    0,   16,    0,   11,    0,
        0,    0,    7,    0,    0,    0,    0,   25,    0,   71,
       72,   73,   74,   75,   76,    0,    0,    0,    0,    0,
       28,   15,   52,   29,   23,   27,   24,    0,   54,   38,
        0,    0,   17,   18,   84,   26,   19,    5,    0,    0,

        0,    0,   33,   40,   53,   77,   78,   79,   80,   81,
       82,   69,   68,   83,    0,    0,    0,    0,    0,   36,
       43,   44,   35,   42,   32,   39,   55,   86,   85,   37,
       34,   41,    0,   20,    0,    9,   12,    0,    0,   46,
       31,   30,    0,    0,    0,    0,    0,    0,    0,   49,
       48,   45,   47,   21,    0,    6,   10,   13,   51,   50,
       56,   57,   58,   59,   60,   61,   22,   62,   63,   64,
       65,   66,   67,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    1,    1,    7,
        8,    1,    9,    1,    9,   10,    1,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,   13,    1,
        1,    1,    1,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,    1,    1,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   15,   16,   17,   18,

       19,   20,   21,   22,   23,    1,    1,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[36] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[177] =
    {   0,
        0,    0,  206,  207,  203,   33,   35,   35,  193,   34,
        0,   38,   24,   32,   39,   32,  179,  191,   30,   33,
      171,   38,   48,   41,  170,  197,   69,  193,  186,   65,
       70,   30,    0,  185,   71,  177,  176,  164,   51,   60,
      173,   64,   56,  163,  179,  155,  156,   74,   70,  163,
      165,  153,  153,  155,  150,  150,   69,  148,  207,  163,
      146,  172,  171,  164,  163,  145,   72,   71,  141,  151,
      150,  149,  148,  147,  146,  134,  133,  139,  130,   86,
       75,  207,  207,  130,  207,   77,   78,  129,  207,  207,
       63,  137,  207,  207,  207,   91,   89,  104,  106,  150,

      146,  128,  207,  135,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,   96,  125,   99,  102,  134,  207,
      132,  207,  207,  131,  207,  130,  207,  207,  207,  207,
      207,  129,  122,  207,   90,  207,  207,  117,  139,  207,
      207,  207,  106,  115,  114,  113,  112,  111,  110,  207,
      207,  207,  207,  109,  128,  127,  207,  207,  207,  207,
      117,  116,  115,  113,  112,  110,  207,  207,  207,  207,
      207,  207,  207,  207,  123,   58
    } ;

static yyconst short int yy_def[177] =
    {   0,
      174,    1,  174,  174,  174,  174,  174,  174,  174,  174,
      175,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  176,  174,  174,
      174,  174,  175,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  176,  176,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,

      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,    0,  174,  174
    } ;

static yyconst short int yy_nxt[243] =
    {   0,
        4,    5,    6,    7,    4,    8,    4,    4,    9,    4,
       10,    4,   11,   12,   13,   14,   15,   16,    4,    4,
        4,   17,    4,   18,   19,   20,   21,   22,    4,   23,
       24,    4,    4,    4,   25,   27,   27,   27,   27,   28,
       32,   36,   45,   29,   31,   30,   34,   65,   35,   37,
       38,   51,   39,   43,   46,   40,   49,   41,   62,   52,
       66,   42,   50,   44,   54,   57,   58,   55,   59,   71,
       56,   27,   27,   60,   64,   30,   32,   67,   73,   78,
       31,   35,   72,   76,   48,   83,   79,   84,   93,  101,
      103,   74,  128,  129,  120,   77,  123,  125,  155,   94,

      156,  104,  102,   85,  116,  121,  117,  124,  126,  118,
      131,  119,  133,  136,   98,  141,   99,  145,  142,  134,
      147,  132,  135,   33,  157,  159,  143,  138,  160,  173,
      146,  172,  171,  148,  170,  169,  168,  156,  156,  167,
      166,  165,  164,  163,  162,  161,  158,  154,  153,  152,
      151,  150,  149,  144,  140,  139,  138,  137,  130,  127,
      122,  115,  114,  113,  112,  111,  110,  109,  108,  107,
      106,  105,  100,   99,   98,   63,   63,   97,   96,   95,
       92,   91,   90,   89,   88,   87,   86,   82,   81,   45,
       80,   75,   70,   69,   68,   35,   30,   63,   26,   61,

       53,   48,   47,   31,   26,  174,    3,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174
    } ;

static yyconst short int yy_chk[243] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    6,    6,    7,    7,    8,
       10,   13,   16,    8,   10,    8,   12,   32,   12,   13,
       14,   20,   14,   15,   16,   14,   19,   14,  176,   20,
       32,   14,   19,   15,   22,   23,   23,   22,   24,   39,
       22,   27,   27,   24,   30,   30,   31,   35,   40,   43,
       31,   35,   39,   42,   48,   48,   43,   49,   57,   67,
       68,   40,   91,   91,   81,   42,   86,   87,  135,   57,

      135,   68,   67,   49,   80,   81,   80,   86,   87,   80,
       96,   80,   97,   99,   98,  115,   99,  117,  115,   97,
      118,   96,   98,  175,  138,  143,  115,  138,  143,  166,
      117,  165,  164,  118,  163,  162,  161,  156,  155,  154,
      149,  148,  147,  146,  145,  144,  139,  133,  132,  126,
      124,  121,  119,  116,  104,  102,  101,  100,   92,   88,
       84,   79,   78,   77,   76,   75,   74,   73,   72,   71,
       70,   69,   66,   65,   64,   63,   62,   61,   60,   58,
       56,   55,   54,   53,   52,   51,   50,   47,   46,   45,
       44,   41,   38,   37,   36,   34,   29,   28,   26,   25,

       21,   18,   17,    9,    5,    3,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "uscan.l"
#define INITIAL 0
#line 2 "uscan.l"
/**************************************************************************
 * uCode Scanner Specification
 *   The scanner reads individual tokens that are then "parsed" by the
 *   uMachine loader.
 *************************************************************************/
#include "uscan.h"

uTOKEN yytok;
#line 440 "lex.yy.cc"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif


#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyFlexLexer::yylex()
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 29 "uscan.l"

#line 569 "lex.yy.cc"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = &cin;

		if ( ! yyout )
			yyout = &cout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 175 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 207 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 30 "uscan.l"
{ yytok =  tWhitespace;     return 1; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 31 "uscan.l"
{ yytok =  tComment;        return 1; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 32 "uscan.l"
{ yytok =  tEOLN;           return 1; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 34 "uscan.l"
{ yytok =  tImmediate;      return 1; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 35 "uscan.l"
{ yytok =  tImmediateF;		return 1; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 36 "uscan.l"
{ yytok = tImmediateF;   return 1; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 37 "uscan.l"
{ yytok = tImmediateS; return 1; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 39 "uscan.l"
{ yytok =  tRegister;       return 1; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 40 "uscan.l"
{ yytok =  tIndexed;        return 1; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 41 "uscan.l"
{ yytok =  tIndirect;       return 1; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 43 "uscan.l"
{ yytok =  tStackRegister;  return 1; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 44 "uscan.l"
{ yytok =  tStackIndexed;   return 1; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 45 "uscan.l"
{ yytok =  tStackIndirect;  return 1; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 47 "uscan.l"
{ yytok =  tLabel;          return 1; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 49 "uscan.l"
{ yytok =  tHLT;            return 1; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 51 "uscan.l"
{ yytok =  tRD;             return 1; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 52 "uscan.l"
{ yytok =  tRDF;			return 1; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 53 "uscan.l"
{ yytok =  tRDS;			return 1; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 54 "uscan.l"
{ yytok =  tWRT;            return 1; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 55 "uscan.l"
{ yytok =  tWRTS;           return 1; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 56 "uscan.l"
{ yytok =  tWRTLN;          return 1; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 57 "uscan.l"
{ yytok =  tWRTLNS;         return 1; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 59 "uscan.l"
{ yytok =  tMOV;            return 1; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 60 "uscan.l"
{ yytok =  tNEG;            return 1; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 61 "uscan.l"
{ yytok =  tADD;            return 1; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 62 "uscan.l"
{ yytok =  tSUB;            return 1; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 63 "uscan.l"
{ yytok =  tMUL;            return 1; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 64 "uscan.l"
{ yytok =  tDIV;            return 1; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 65 "uscan.l"
{ yytok =  tMOD;			  return 1; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 67 "uscan.l"
{ yytok = tCASTI;        return 1; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 68 "uscan.l"
{ yytok = tCASTF;        return 1; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 70 "uscan.l"
{ yytok =  tNEGF;           return 1; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 71 "uscan.l"
{ yytok =  tADDF;           return 1; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 72 "uscan.l"
{ yytok =  tSUBF;           return 1; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 73 "uscan.l"
{ yytok =  tMULF;           return 1; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 74 "uscan.l"
{ yytok =  tDIVF;           return 1; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 76 "uscan.l"
{ yytok =  tPUSH;           return 1; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 77 "uscan.l"
{ yytok =  tPOP ;           return 1; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 78 "uscan.l"
{ yytok =  tNEGS;           return 1; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 79 "uscan.l"
{ yytok =  tADDS;           return 1; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 80 "uscan.l"
{ yytok =  tSUBS;           return 1; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 81 "uscan.l"
{ yytok =  tMULS;           return 1; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 82 "uscan.l"
{ yytok =  tDIVS;           return 1; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 83 "uscan.l"
{ yytok =  tMODS;			  return 1; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 85 "uscan.l"
{ yytok =  tNEGSF;           return 1; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 86 "uscan.l"
{ yytok =  tADDSF;           return 1; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 87 "uscan.l"
{ yytok =  tSUBSF;           return 1; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 88 "uscan.l"
{ yytok =  tMULSF;           return 1; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 89 "uscan.l"
{ yytok =  tDIVSF;           return 1; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 91 "uscan.l"
{ yytok = tCASTSI;        return 1; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 92 "uscan.l"
{ yytok = tCASTSF;        return 1; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 94 "uscan.l"
{ yytok =  tLAB ;           return 1; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 96 "uscan.l"
{ yytok = tANDS;		return 1; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 97 "uscan.l"
{ yytok = tORS;			return 1; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 98 "uscan.l"
{ yytok = tNOTS;		return 1; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 100 "uscan.l"
{ yytok = tCMPEQS;		return 1; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 101 "uscan.l"
{ yytok = tCMPGES;		return 1; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 102 "uscan.l"
{ yytok = tCMPGTS;		return 1; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 103 "uscan.l"
{ yytok = tCMPLES;		return 1; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 104 "uscan.l"
{ yytok = tCMPLTS;		return 1; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 105 "uscan.l"
{ yytok = tCMPNES;		return 1; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 107 "uscan.l"
{ yytok = tCMPEQSF;		return 1; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 108 "uscan.l"
{ yytok = tCMPGESF;		return 1; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 109 "uscan.l"
{ yytok = tCMPGTSF;		return 1; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 110 "uscan.l"
{ yytok = tCMPLESF;		return 1; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 111 "uscan.l"
{ yytok = tCMPLTSF;		return 1; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 112 "uscan.l"
{ yytok = tCMPNESF;		return 1; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 114 "uscan.l"
{ yytok = tBRTS;			  return 1; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 115 "uscan.l"
{ yytok = tBRFS;			  return 1; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 117 "uscan.l"
{ yytok =  tBR  ;           return 1; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 118 "uscan.l"
{ yytok =  tBEQ ;           return 1; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 119 "uscan.l"
{ yytok =  tBGE ;           return 1; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 120 "uscan.l"
{ yytok =  tBGT ;           return 1; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 121 "uscan.l"
{ yytok =  tBLE ;           return 1; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 122 "uscan.l"
{ yytok =  tBLT ;           return 1; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 123 "uscan.l"
{ yytok =  tBNE ;           return 1; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 125 "uscan.l"
{ yytok =  tBEQF ;          return 1; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 126 "uscan.l"
{ yytok =  tBGEF ;          return 1; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 127 "uscan.l"
{ yytok =  tBGTF ;          return 1; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 128 "uscan.l"
{ yytok =  tBLEF ;          return 1; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 129 "uscan.l"
{ yytok =  tBLTF ;          return 1; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 130 "uscan.l"
{ yytok =  tBNEF ;          return 1; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 132 "uscan.l"
{ yytok =  tCALL;           return 1; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 133 "uscan.l"
{ yytok =  tRET ;           return 1; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 135 "uscan.l"
{ yytok =  tPRTS;           return 1; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 136 "uscan.l"
{ yytok =  tPRTR;           return 1; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 137 "uscan.l"
{ yytok =  tEOF;            return 1; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 140 "uscan.l"
{
                    /* Unknown character found (error) */
					int inChar = yyinput();
					printf("uscan.l: Unrecognzied character:%c.\n", inChar);

                    while (  ((char) inChar != '\0')
                          && ((char) inChar != '\n')
                          && ((char) inChar != '\t')
                          && ((char) inChar != ' ' ))
                    {
                      yytext[yyleng++] = inChar;
                      inChar = yyinput();
					  printf("uscan.l: Unrecognzied character:%c.\n", inChar);
                    }

                    yytext[yyleng] = '\0';
                    unput(inChar);

                    yytok = tError;
                    return 1;
                  }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 161 "uscan.l"
ECHO;
	YY_BREAK
#line 1116 "lex.yy.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */

yyFlexLexer::yyFlexLexer( istream* arg_yyin, ostream* arg_yyout )
	{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 1;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = 0;

	yy_current_buffer = 0;

#ifdef YY_USES_REJECT
	yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
	yy_state_buf = 0;
#endif
	}

yyFlexLexer::~yyFlexLexer()
	{
	delete yy_state_buf;
	yy_delete_buffer( yy_current_buffer );
	}

void yyFlexLexer::switch_streams( istream* new_in, ostream* new_out )
	{
	if ( new_in )
		{
		yy_delete_buffer( yy_current_buffer );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
		}

	if ( new_out )
		yyout = new_out;
	}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
	{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
	}

void yyFlexLexer::LexerOutput( const char* buf, int size )
	{
	(void) yyout->write( buf, size );
	}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

int yyFlexLexer::yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 175 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 175 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 174);

	return yy_is_jam ? 0 : yy_current_state;
	}


void yyFlexLexer::yyunput( int c, register char* yy_bp )
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}


int yyFlexLexer::yyinput()
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


void yyFlexLexer::yyrestart( istream* input_file )
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


void yyFlexLexer::yy_load_buffer_state()
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( istream* file, int size )
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


extern "C" int isatty YY_PROTO(( int ));
void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, istream* file )

	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

	b->yy_is_interactive = 0;
	}


void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif


void yyFlexLexer::LexerError( yyconst char msg[] )
	{
	cerr << msg << '\n';
	exit( YY_EXIT_FAILURE );
	}


/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 161 "uscan.l"


#line 2 "C:/Users/Aidan/Git/uMachine/machine/uscan.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 88
#define YY_END_OF_BUFFER 89
static yyconst short int yy_accept[175] =
    {   0,
        0,    0,   89,   87,    1,    3,    3,   87,   87,   87,
        2,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,    1,    3,    0,    0,    4,
        0,    0,    2,    0,    0,    0,    0,    0,    0,    0,
        0,   70,    0,    0,    8,    0,    0,   14,    0,    0,
        0,    0,    0,    0,    0,    0,   16,    0,   11,    0,
        0,    0,    7,    0,    0,    0,    0,   25,    0,   71,
       72,   73,   74,   75,   76,    0,    0,    0,    0,    0,
       28,   15,   52,   29,   23,   27,   24,    0,   54,   38,
        0,    0,   17,   18,   84,   26,   19,    5,    0,    0,

        0,    0,   33,   40,   53,   77,   78,   79,   80,   81,
       82,   69,   68,   83,    0,    0,    0,    0,    0,   36,
       43,   44,   35,   42,   32,   39,   55,   86,   85,   37,
       34,   41,    0,   20,    0,    9,   12,    0,    0,   46,
       31,   30,    0,    0,    0,    0,    0,    0,    0,   49,
       48,   45,   47,   21,    0,    6,   10,   13,   51,   50,
       56,   57,   58,   59,   60,   61,   22,   62,   63,   64,
       65,   66,   67,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    1,    1,    7,
        8,    1,    9,    1,    9,   10,    1,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,   13,    1,
        1,    1,    1,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,    1,    1,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   15,   16,   17,   18,

       19,   20,   21,   22,   23,    1,    1,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[36] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[177] =
    {   0,
        0,    0,  206,  207,  203,   33,   35,   35,  193,   34,
        0,   38,   24,   32,   39,   32,  179,  191,   30,   33,
      171,   38,   48,   41,  170,  197,   69,  193,  186,   65,
       70,   30,    0,  185,   71,  177,  176,  164,   51,   60,
      173,   64,   56,  163,  179,  155,  156,   74,   70,  163,
      165,  153,  153,  155,  150,  150,   69,  148,  207,  163,
      146,  172,  171,  164,  163,  145,   72,   71,  141,  151,
      150,  149,  148,  147,  146,  134,  133,  139,  130,   86,
       75,  207,  207,  130,  207,   77,   78,  129,  207,  207,
       63,  137,  207,  207,  207,   91,   89,  104,  106,  150,

      146,  128,  207,  135,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,   96,  125,   99,  102,  134,  207,
      132,  207,  207,  131,  207,  130,  207,  207,  207,  207,
      207,  129,  122,  207,   90,  207,  207,  117,  139,  207,
      207,  207,  106,  115,  114,  113,  112,  111,  110,  207,
      207,  207,  207,  109,  128,  127,  207,  207,  207,  207,
      117,  116,  115,  113,  112,  110,  207,  207,  207,  207,
      207,  207,  207,  207,  123,   58
    } ;

static yyconst short int yy_def[177] =
    {   0,
      174,    1,  174,  174,  174,  174,  174,  174,  174,  174,
      175,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  176,  174,  174,
      174,  174,  175,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  176,  176,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,

      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,    0,  174,  174
    } ;

static yyconst short int yy_nxt[243] =
    {   0,
        4,    5,    6,    7,    4,    8,    4,    4,    9,    4,
       10,    4,   11,   12,   13,   14,   15,   16,    4,    4,
        4,   17,    4,   18,   19,   20,   21,   22,    4,   23,
       24,    4,    4,    4,   25,   27,   27,   27,   27,   28,
       32,   36,   45,   29,   31,   30,   34,   65,   35,   37,
       38,   51,   39,   43,   46,   40,   49,   41,   62,   52,
       66,   42,   50,   44,   54,   57,   58,   55,   59,   71,
       56,   27,   27,   60,   64,   30,   32,   67,   73,   78,
       31,   35,   72,   76,   48,   83,   79,   84,   93,  101,
      103,   74,  128,  129,  120,   77,  123,  125,  155,   94,

      156,  104,  102,   85,  116,  121,  117,  124,  126,  118,
      131,  119,  133,  136,   98,  141,   99,  145,  142,  134,
      147,  132,  135,   33,  157,  159,  143,  138,  160,  173,
      146,  172,  171,  148,  170,  169,  168,  156,  156,  167,
      166,  165,  164,  163,  162,  161,  158,  154,  153,  152,
      151,  150,  149,  144,  140,  139,  138,  137,  130,  127,
      122,  115,  114,  113,  112,  111,  110,  109,  108,  107,
      106,  105,  100,   99,   98,   63,   63,   97,   96,   95,
       92,   91,   90,   89,   88,   87,   86,   82,   81,   45,
       80,   75,   70,   69,   68,   35,   30,   63,   26,   61,

       53,   48,   47,   31,   26,  174,    3,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174
    } ;

static yyconst short int yy_chk[243] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    6,    6,    7,    7,    8,
       10,   13,   16,    8,   10,    8,   12,   32,   12,   13,
       14,   20,   14,   15,   16,   14,   19,   14,  176,   20,
       32,   14,   19,   15,   22,   23,   23,   22,   24,   39,
       22,   27,   27,   24,   30,   30,   31,   35,   40,   43,
       31,   35,   39,   42,   48,   48,   43,   49,   57,   67,
       68,   40,   91,   91,   81,   42,   86,   87,  135,   57,

      135,   68,   67,   49,   80,   81,   80,   86,   87,   80,
       96,   80,   97,   99,   98,  115,   99,  117,  115,   97,
      118,   96,   98,  175,  138,  143,  115,  138,  143,  166,
      117,  165,  164,  118,  163,  162,  161,  156,  155,  154,
      149,  148,  147,  146,  145,  144,  139,  133,  132,  126,
      124,  121,  119,  116,  104,  102,  101,  100,   92,   88,
       84,   79,   78,   77,   76,   75,   74,   73,   72,   71,
       70,   69,   66,   65,   64,   63,   62,   61,   60,   58,
       56,   55,   54,   53,   52,   51,   50,   47,   46,   45,
       44,   41,   38,   37,   36,   34,   29,   28,   26,   25,

       21,   18,   17,    9,    5,    3,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "uscan.l"
#define INITIAL 0
#line 2 "uscan.l"
/**************************************************************************
 * uCode Scanner Specification
 *   The scanner reads individual tokens that are then "parsed" by the
 *   uMachine loader.
 *************************************************************************/
#include "uscan.h"

uTOKEN yytok;
#line 482 "C:/Users/Aidan/Git/uMachine/machine/uscan.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 29 "uscan.l"

#line 635 "C:/Users/Aidan/Git/uMachine/machine/uscan.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 175 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 207 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 30 "uscan.l"
{ yytok =  tWhitespace;     return 1; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 31 "uscan.l"
{ yytok =  tComment;        return 1; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 32 "uscan.l"
{ yytok =  tEOLN;           return 1; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 34 "uscan.l"
{ yytok =  tImmediate;      return 1; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 35 "uscan.l"
{ yytok =  tImmediateF;		return 1; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 36 "uscan.l"
{ yytok = tImmediateF;   return 1; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 37 "uscan.l"
{ yytok = tImmediateS; return 1; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 39 "uscan.l"
{ yytok =  tRegister;       return 1; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 40 "uscan.l"
{ yytok =  tIndexed;        return 1; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 41 "uscan.l"
{ yytok =  tIndirect;       return 1; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 43 "uscan.l"
{ yytok =  tStackRegister;  return 1; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 44 "uscan.l"
{ yytok =  tStackIndexed;   return 1; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 45 "uscan.l"
{ yytok =  tStackIndirect;  return 1; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 47 "uscan.l"
{ yytok =  tLabel;          return 1; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 49 "uscan.l"
{ yytok =  tHLT;            return 1; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 51 "uscan.l"
{ yytok =  tRD;             return 1; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 52 "uscan.l"
{ yytok =  tRDF;			return 1; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 53 "uscan.l"
{ yytok =  tRDS;			return 1; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 54 "uscan.l"
{ yytok =  tWRT;            return 1; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 55 "uscan.l"
{ yytok =  tWRTS;           return 1; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 56 "uscan.l"
{ yytok =  tWRTLN;          return 1; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 57 "uscan.l"
{ yytok =  tWRTLNS;         return 1; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 59 "uscan.l"
{ yytok =  tMOV;            return 1; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 60 "uscan.l"
{ yytok =  tNEG;            return 1; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 61 "uscan.l"
{ yytok =  tADD;            return 1; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 62 "uscan.l"
{ yytok =  tSUB;            return 1; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 63 "uscan.l"
{ yytok =  tMUL;            return 1; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 64 "uscan.l"
{ yytok =  tDIV;            return 1; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 65 "uscan.l"
{ yytok =  tMOD;			  return 1; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 67 "uscan.l"
{ yytok = tCASTI;        return 1; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 68 "uscan.l"
{ yytok = tCASTF;        return 1; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 70 "uscan.l"
{ yytok =  tNEGF;           return 1; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 71 "uscan.l"
{ yytok =  tADDF;           return 1; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 72 "uscan.l"
{ yytok =  tSUBF;           return 1; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 73 "uscan.l"
{ yytok =  tMULF;           return 1; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 74 "uscan.l"
{ yytok =  tDIVF;           return 1; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 76 "uscan.l"
{ yytok =  tPUSH;           return 1; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 77 "uscan.l"
{ yytok =  tPOP ;           return 1; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 78 "uscan.l"
{ yytok =  tNEGS;           return 1; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 79 "uscan.l"
{ yytok =  tADDS;           return 1; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 80 "uscan.l"
{ yytok =  tSUBS;           return 1; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 81 "uscan.l"
{ yytok =  tMULS;           return 1; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 82 "uscan.l"
{ yytok =  tDIVS;           return 1; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 83 "uscan.l"
{ yytok =  tMODS;			  return 1; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 85 "uscan.l"
{ yytok =  tNEGSF;           return 1; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 86 "uscan.l"
{ yytok =  tADDSF;           return 1; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 87 "uscan.l"
{ yytok =  tSUBSF;           return 1; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 88 "uscan.l"
{ yytok =  tMULSF;           return 1; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 89 "uscan.l"
{ yytok =  tDIVSF;           return 1; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 91 "uscan.l"
{ yytok = tCASTSI;        return 1; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 92 "uscan.l"
{ yytok = tCASTSF;        return 1; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 94 "uscan.l"
{ yytok =  tLAB ;           return 1; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 96 "uscan.l"
{ yytok = tANDS;		return 1; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 97 "uscan.l"
{ yytok = tORS;			return 1; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 98 "uscan.l"
{ yytok = tNOTS;		return 1; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 100 "uscan.l"
{ yytok = tCMPEQS;		return 1; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 101 "uscan.l"
{ yytok = tCMPGES;		return 1; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 102 "uscan.l"
{ yytok = tCMPGTS;		return 1; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 103 "uscan.l"
{ yytok = tCMPLES;		return 1; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 104 "uscan.l"
{ yytok = tCMPLTS;		return 1; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 105 "uscan.l"
{ yytok = tCMPNES;		return 1; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 107 "uscan.l"
{ yytok = tCMPEQSF;		return 1; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 108 "uscan.l"
{ yytok = tCMPGESF;		return 1; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 109 "uscan.l"
{ yytok = tCMPGTSF;		return 1; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 110 "uscan.l"
{ yytok = tCMPLESF;		return 1; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 111 "uscan.l"
{ yytok = tCMPLTSF;		return 1; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 112 "uscan.l"
{ yytok = tCMPNESF;		return 1; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 114 "uscan.l"
{ yytok = tBRTS;			  return 1; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 115 "uscan.l"
{ yytok = tBRFS;			  return 1; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 117 "uscan.l"
{ yytok =  tBR  ;           return 1; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 118 "uscan.l"
{ yytok =  tBEQ ;           return 1; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 119 "uscan.l"
{ yytok =  tBGE ;           return 1; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 120 "uscan.l"
{ yytok =  tBGT ;           return 1; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 121 "uscan.l"
{ yytok =  tBLE ;           return 1; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 122 "uscan.l"
{ yytok =  tBLT ;           return 1; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 123 "uscan.l"
{ yytok =  tBNE ;           return 1; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 125 "uscan.l"
{ yytok =  tBEQF ;          return 1; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 126 "uscan.l"
{ yytok =  tBGEF ;          return 1; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 127 "uscan.l"
{ yytok =  tBGTF ;          return 1; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 128 "uscan.l"
{ yytok =  tBLEF ;          return 1; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 129 "uscan.l"
{ yytok =  tBLTF ;          return 1; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 130 "uscan.l"
{ yytok =  tBNEF ;          return 1; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 132 "uscan.l"
{ yytok =  tCALL;           return 1; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 133 "uscan.l"
{ yytok =  tRET ;           return 1; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 135 "uscan.l"
{ yytok =  tPRTS;           return 1; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 136 "uscan.l"
{ yytok =  tPRTR;           return 1; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 137 "uscan.l"
{ yytok =  tEOF;            return 1; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 140 "uscan.l"
{
                    /* Unknown character found (error) */
					int inChar = yyinput();
					printf("uscan.l: Unrecognzied character:%c.\n", inChar);

                    while (  ((char) inChar != '\0')
                          && ((char) inChar != '\n')
                          && ((char) inChar != '\t')
                          && ((char) inChar != ' ' ))
                    {
                      yytext[yyleng++] = inChar;
                      inChar = yyinput();
					  printf("uscan.l: Unrecognzied character:%c.\n", inChar);
                    }

                    yytext[yyleng] = '\0';
                    unput(inChar);

                    yytok = tError;
                    return 1;
                  }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 161 "uscan.l"
ECHO;
	YY_BREAK
#line 1182 "C:/Users/Aidan/Git/uMachine/machine/uscan.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 175 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 175 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 174);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern "C" int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 161 "uscan.l"


